//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misa.FastCode.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misa.FastCode.Common.Resource.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoạc mật khẩu không đúng.
        /// </summary>
        public static string CredentialnvalidError {
            get {
                return ResourceManager.GetString("CredentialnvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu dữ liệu không hợp lệ.
        /// </summary>
        public static string DataTypeError {
            get {
                return ResourceManager.GetString("DataTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị hao mòn năm phải bằng tỷ lệ hao mòn * nguyên giá.
        /// </summary>
        public static string DepAnnualCostDepRateError {
            get {
                return ResourceManager.GetString("DepAnnualCostDepRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ hao mòn phải bằng 1 / số năm sử dụng.
        /// </summary>
        public static string DepRateLifeTimeError {
            get {
                return ResourceManager.GetString("DepRateLifeTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đã tồn tại ở bản ghi số {0}.
        /// </summary>
        public static string DuplicateCodeAboveError {
            get {
                return ResourceManager.GetString("DuplicateCodeAboveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng lặp {0}.
        /// </summary>
        public static string DuplicateCodeError {
            get {
                return ResourceManager.GetString("DuplicateCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị {0} phải bằng {1}.
        /// </summary>
        public static string EqualError {
            get {
                return ResourceManager.GetString("EqualError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số cột phải bằng {0}.
        /// </summary>
        public static string FileColumnError {
            get {
                return ResourceManager.GetString("FileColumnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu trong tệp không hợp lệ.
        /// </summary>
        public static string FileDataError {
            get {
                return ResourceManager.GetString("FileDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File bị lỗi.
        /// </summary>
        public static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không đúng định dạng.
        /// </summary>
        public static string FileFormatError {
            get {
                return ResourceManager.GetString("FileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dòng không hợp lệ.
        /// </summary>
        public static string FileRowError {
            get {
                return ResourceManager.GetString("FileRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị {0} phải lớn hơn {1}.
        /// </summary>
        public static string HigherError {
            get {
                return ResourceManager.GetString("HigherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống, vui lòng liên hệ Misa.
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị {0} không hợp lệ.
        /// </summary>
        public static string InvalidError {
            get {
                return ResourceManager.GetString("InvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài {0} phải từ {1} đến {2}.
        /// </summary>
        public static string LengthError {
            get {
                return ResourceManager.GetString("LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị {0} phải nhỏ hơn {1}.
        /// </summary>
        public static string LowerError {
            get {
                return ResourceManager.GetString("LowerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại {0}.
        /// </summary>
        public static string NotExistedError {
            get {
                return ResourceManager.GetString("NotExistedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa {0} vì {0} không tồn tại.
        /// </summary>
        public static string NotFoundDeleteError {
            get {
                return ResourceManager.GetString("NotFoundDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa vì có bản ghi trong danh sách không tồn tại.
        /// </summary>
        public static string NotFoundDeleteListError {
            get {
                return ResourceManager.GetString("NotFoundDeleteListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy {0} vì {0} không tồn tại.
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật {0} vì {0} không tồn tại.
        /// </summary>
        public static string NotFoundUpdateError {
            get {
                return ResourceManager.GetString("NotFoundUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị {0} phải lớn hơn 0.
        /// </summary>
        public static string PositiveNumberError {
            get {
                return ResourceManager.GetString("PositiveNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị {0} phải từ {1} đến {2}.
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được phép để trống {0}.
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên đăng nhập của bạn đã hết, vui lòng đăng nhập lại.
        /// </summary>
        public static string TokenInvalidError {
            get {
                return ResourceManager.GetString("TokenInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua không được nhỏ hơn ngày sử dụng.
        /// </summary>
        public static string UseDateLessThanPurchaseDateError {
            get {
                return ResourceManager.GetString("UseDateLessThanPurchaseDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu thêm mới không hợp lệ.
        /// </summary>
        public static string ValidateCreateError {
            get {
                return ResourceManager.GetString("ValidateCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu lọc không hợp lệ.
        /// </summary>
        public static string ValidateFilterError {
            get {
                return ResourceManager.GetString("ValidateFilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu cập nhật không hợp lệ.
        /// </summary>
        public static string ValidateUpdateError {
            get {
                return ResourceManager.GetString("ValidateUpdateError", resourceCulture);
            }
        }
    }
}
